"""Remove is_active column, activity now derived from sample recency

Revision ID: 6acb9e95f8c2
Revises: fb2c9e060837
Create Date: 2026-09-29 17:41:45.647619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acb9e95f8c2'
down_revision = 'fb2c9e060837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('COLLECTION_INSTANCE', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('RISK_SCORE_HISTORY', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('computed_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RISK_SCORE_HISTORY', schema=None) as batch_op:
        batch_op.alter_column('computed_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('COLLECTION_INSTANCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
