"""v2 schema: collection instances, factor groups

Revision ID: c346cafefa06
Revises: 
Create Date: 2026-09-23 13:51:50.535382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c346cafefa06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BMS_SUBSYSTEM',
    sa.Column('id_subsystem', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_subsystem')
    )
    op.create_table('FACTOR_GROUP',
    sa.Column('id_factor_group', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_factor_group')
    )
    op.create_table('DEVICE_TYPE',
    sa.Column('id_device_type', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('primary_data_collected', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id_subsystem', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_subsystem'], ['BMS_SUBSYSTEM.id_subsystem'], ),
    sa.PrimaryKeyConstraint('id_device_type')
    )
    op.create_table('RISK_FACTOR',
    sa.Column('id_factor', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id_factor_group', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_factor_group'], ['FACTOR_GROUP.id_factor_group'], ),
    sa.PrimaryKeyConstraint('id_factor')
    )
    op.create_table('DEVICE',
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id_device_type', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device_type'], ['DEVICE_TYPE.id_device_type'], ),
    sa.PrimaryKeyConstraint('id_device')
    )
    op.create_table('COLLECTION_INSTANCE',
    sa.Column('id_instance', sa.String(length=36), nullable=False),
    sa.Column('data_description', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['DEVICE.id_device'], ),
    sa.PrimaryKeyConstraint('id_instance')
    )
    op.create_table('DEVICE_DATA_SAMPLE',
    sa.Column('id_sample', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('data_value', sa.String(length=50), nullable=True),
    sa.Column('id_instance', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_instance'], ['COLLECTION_INSTANCE.id_instance'], ),
    sa.PrimaryKeyConstraint('id_sample')
    )
    op.create_table('INSTANCE_FACTOR_SCORE',
    sa.Column('id_instance_factor_score', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id_instance', sa.String(length=36), nullable=False),
    sa.Column('id_factor', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_factor'], ['RISK_FACTOR.id_factor'], ),
    sa.ForeignKeyConstraint(['id_instance'], ['COLLECTION_INSTANCE.id_instance'], ),
    sa.PrimaryKeyConstraint('id_instance_factor_score')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INSTANCE_FACTOR_SCORE')
    op.drop_table('DEVICE_DATA_SAMPLE')
    op.drop_table('COLLECTION_INSTANCE')
    op.drop_table('DEVICE')
    op.drop_table('RISK_FACTOR')
    op.drop_table('DEVICE_TYPE')
    op.drop_table('FACTOR_GROUP')
    op.drop_table('BMS_SUBSYSTEM')
    # ### end Alembic commands ###
