"""Replace is_active with raw category attributes on CollectionInstance

Revision ID: f955440ea50b
Revises: 6acb9e95f8c2
Create Date: 2026-09-29 18:00:42.376619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f955440ea50b'
down_revision = '6acb9e95f8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('COLLECTION_INSTANCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nature', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('identifiability_level', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('location_scope', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('collection_frequency', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('access_scope', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('sharing_scope', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('COLLECTION_INSTANCE', schema=None) as batch_op:
        batch_op.drop_column('sharing_scope')
        batch_op.drop_column('access_scope')
        batch_op.drop_column('collection_frequency')
        batch_op.drop_column('location_scope')
        batch_op.drop_column('identifiability_level')
        batch_op.drop_column('data_nature')

    # ### end Alembic commands ###
