"""Add RiskScoreHistory table

Revision ID: fb2c9e060837
Revises: c346cafefa06
Create Date: 2026-09-24 17:10:09.599054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2c9e060837'
down_revision = 'c346cafefa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RISK_SCORE_HISTORY',
    sa.Column('id_history', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.Date(), nullable=False),
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['DEVICE.id_device'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RISK_SCORE_HISTORY')
    # ### end Alembic commands ###
